### ISSUE TITLE
Matching results of CasHash_CUDA are fewer than other matching algorithm, such as brute force

### ISSUE THREAD

**Issue by crystal28** [cvcore/cashash_cuda#9]
Hi,all
    I use CasHash_CUDA in my project, It has fast operating speed. But I found a problem, it has fewer matching results than brute force algorithm, I worry about fewer matching points will cause following bundle adjustment unstable .
    There's a coefficient (it's value is 0.32f )in the function of GeneratePairKernelFast in HashMatcher.cu:
`if(min1.dist < min2.dist * 0.32f) {
            g_pairResult[queryIndex] = min1.index;
        } else {
            g_pairResult[queryIndex] = INVALID_CANDIDATE;
        }`
    I raise the coefficient, and get more matching results, but some of them are not correct. Can anyone give me some advice?
    Thanks a lot.

**Comment by alien19** [comment]
Hello @crystal28, Have you reached a solid understanding of how the CasHash algorithm return much fewer matches than Brute force algorithm or even KMeans?
